name: traffic-sign
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - matplotlib
    - jupyter
    - opencv3
    - pillow
    - scikit-learn
    - scipy
    - h5py
    - seaborn
    - pandas
    - pip:
        - tensorflow==0.12.1
